name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          platforms: ${{ steps.buildx.outputs.platforms }}
          context: .
          tags: ghcr.io/${{ github.actor }}/gol:latest,ghcr.io/${{ github.actor }}/gol:${{ github.ref_name }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
